/**
 * Factory function for creating Nucleus instances
 */

import { Nucleus } from "./nucleus.js";
import type { RecordStore } from "../types/index.js";

/**
 * Configuration for creating a Nucleus instance
 */
export interface CreateNucleusConfig {
  /** Storage adapter */
  storage: RecordStore;

  /** Optional path to WASM module (defaults to bundled WASM) */
  wasmPath?: string;
}

/**
 * Create a Nucleus instance with WASM hash computation
 * 
 * This factory function:
 * 1. Loads the WASM module for hash computation
 * 2. Creates compute_hash function wrapper
 * 3. Returns configured Nucleus instance
 * 
 * Note: Modules must be registered separately via registerModule()
 * 
 * @param config Nucleus configuration
 * @returns Configured Nucleus instance
 * 
 * @example
 * ```typescript
 * import { createNucleus, registerModule } from '@onoal/nucleus';
 * import { SQLiteRecordStore } from '@onoal/nucleus/storage-sqlite';
 * import { oidModule, proofModule } from '@onoal/nucleus';
 * 
 * // 1. Register modules
 * registerModule('oid', oidModule);
 * registerModule('proof', proofModule);
 * 
 * // 2. Create Nucleus instance
 * const nucleus = await createNucleus({
 *   storage: new SQLiteRecordStore('./nucleus.db')
 * });
 * 
 * // 3. Use it
 * await nucleus.append({
 *   module: 'oid',
 *   chainId: 'oid:onoal:user123',
 *   body: { oidRecord: {...} }
 * });
 * ```
 */
export async function createNucleus(config: CreateNucleusConfig): Promise<Nucleus> {
  // Load WASM module
  // Note: In v0.1.0-beta, we expect WASM to be built and available
  // The actual import will be done dynamically when WASM is built
  let wasm: { compute_hash: (record: unknown) => string };

  try {
    // Dynamic import of WASM module
    // This will be generated by wasm-pack
    wasm = await import("../wasm/nucleus_core_rs.js");
  } catch (error) {
    throw new Error(
      `Failed to load WASM module. Make sure to run 'pnpm build:wasm' first. ` +
        `Error: ${error instanceof Error ? error.message : String(error)}`
    );
  }

  // Create compute hash function wrapper
  const computeHash = (recordWithoutHash: Record<string, unknown>): string => {
    try {
      return wasm.compute_hash(recordWithoutHash);
    } catch (error) {
      throw new Error(
        `WASM hash computation failed: ${error instanceof Error ? error.message : String(error)}`
      );
    }
  };

  // Return configured Nucleus instance
  return new Nucleus(config.storage, computeHash);
}

